server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    max-connections: 10000
    threads:
      max: 500
      min-spare: 10
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2048MB
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        max-active: 3000
        max-idle: 100
        max-wait: 2500
        min-idle: 0
  datasource:
    url: jdbc:mysql://192.168.24.130:12345/filedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# knife4j增强
knife4j:
  enable: true

file:
  #存储类型 对应的存储服务器配置要开启才可以正常使用
  storage: fastdfs
  #普通上传文件最大值
  max-upload-size: 5MB
  #分片文件最小值 小于5M minio会上传错误
  multipart-min-size: 5MB
  #分片文件最大值
  multipart-max-size: 100MB
#fastdfs 配置
fastdfs:
  enabled: true
  # tracker服务
  tracker-servers: "192.168.24.130:22122"
  # 固定分组
#  default-group: "group1"
  http:
    # web访问地址
    web-server-url: "http://192.168.24.130:8888"
    # web访问地址是否包含group
    web-server-url-has-group: true
    # 开启防盗链
    http-anti-steal-token: true
    # 防盗链密钥
    secret-key: "FastDFS1234567890"
  connection:
    #scoket超时
    socket-timeout: 30000
    #连接超时
    connect-timeout: 2000
    #tracker重试
    retry-after-second: 30
    pool:
      max-wait-millis: 5000
      max-total-per-key: 500
      max-idle-per-key: 100
      min-idle-per-key: 10
      min-evictable-idle-time-millis: 1800000
      soft-min-evictable-idle-time-millis: 60000
      test-on-borrow: true

# 健康检查端点 actuator/fastdfs
management:
  endpoints:
    web:
      exposure:
        include: 'fastdfs'

s3:
  enabled: false

